/**
 * Bundle the CLIENT half of dsh-agents-bridge (`src/client/index.ts` →
 * `lib/client.js`).
 *
 * WHAT MAKES THIS DIFFERENT FROM `build.mjs`
 * ------------------------------------------
 * The Node half is ESM for Node; this half is a browser module consumed by the
 * DSH web client's module table, so it must be:
 *
 *   - `platform: 'browser'` — no `node:` builtins, no `process` shim;
 *   - `format: 'cjs'` — the module table calls a CommonJS-shaped `factory`,
 *     not an ES module `import()`;
 *   - `target: 'es2020'` — the widest engine set a desktop shell might embed,
 *     while still allowing `?.`/`??`.
 *
 * THE WRAPPER IS THE CONTRACT, NOT DECORATION
 * -------------------------------------------
 * The host does NOT `import()` this file and read its exports. At startup it
 * registers plugin factories through `window.__ModuleLoader__.load({ id,
 * factory })`, and the module body stays lazy until something materialises it
 * (the host's own docs, quoted in `docs/plan.md` § 工作流 G). A bare esbuild CJS
 * artifact therefore loads as a plain script, registers NOTHING, and the UI is
 * silently absent — no error, because nothing ever looks for the bundle. So the
 * emitted file is:
 *
 *   window.__ModuleLoader__.load({ id: <package name>, factory: (require) => {
 *     <esbuild CJS body, unmodified>
 *     return module.exports;
 *   }});
 *
 * `id` comes from `package.json#name` (never a literal): the host keys the
 * module table on it, `src/client/identity.ts` derives the slot ids and
 * registrant from the same value, and `verify_plugin.py` cross-checks all
 * three. A literal would silently disagree after a rename.
 *
 * The CJS body is inserted verbatim: the `factory`'s parameters shadow the
 * `module` / `exports` / `require` the body expects, so the body's
 * `require("react")` resolves to the HOST's copy (see `CLIENT_EXTERNALS` in
 * `scripts/build.mjs`) and never to a bundled second React.
 */
import { build } from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { CLIENT_EXTERNALS } from './build.mjs'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))
const outfile = path.join(root, 'lib/client.js')

const result = await build({
  entryPoints: [path.join(root, 'src/client/index.ts')],
  outfile,
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  sourcemap: false,
  logLevel: 'info',
  // Hold the artifact in memory: it is not the deliverable, the WRAPPED
  // artifact is.
  write: false,
  // `src/client/identity.ts` reads the package name from here — the same
  // `package.json#name` used for the ModuleLoader id below.
  define: { __PACKAGE_NAME__: JSON.stringify(pkg.name) },
  external: CLIENT_EXTERNALS,
})

const [output] = result.outputFiles ?? []
if (output === undefined) {
  throw new Error('esbuild produced no output for the client bundle')
}

const banner = [
  '// Generated by scripts/build-client.mjs — do not edit.',
  '// Registers this plugin\'s client half with the DSH web client\'s module table.',
  `window.__ModuleLoader__.load({ id: ${JSON.stringify(pkg.name)}, factory: (require) => {`,
  '\tvar module = { exports: {} };',
  '\tvar exports = module.exports;',
  '\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '',
].join('\n')

const footer = ['', '\treturn module.exports;', '}', '});', ''].join('\n')

writeFileSync(outfile, `${banner}${output.text}${footer}`)
